server.port=8081

spring.application.name=cellphones-spring

spring.datasource.url=jdbc:postgresql://localhost:5433/cellphones_db
spring.datasource.username=postgres
spring.datasource.password=anhzac12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=CXW9MxzKP90f8zpDSkjTcfbJfHUGh5ABQwErTyUidkdr

api.prefix=/api/v1

google.client-id=566050216696-2d8pe12hamn2igtosqqbsfimos98i8en.apps.googleusercontent.com

spring.jackson.mapper.accept-case-insensitive-enums=true

payos.client-id=d76c74a0-c391-4c96-ab4a-ee5eb1008a9c
payos.api-key=0a7595be-84a9-4ec2-88ae-c5bd25edf0b3
payos.check-sum=aea5b85e9e94f46ff914308d459091e3912fd61e8982a6769408c3139472a90d
