server.port=8081

spring.application.name=cellphones-spring

spring.datasource.url=jdbc:postgresql://localhost:5433/cellphones_db
spring.datasource.username=postgres
spring.datasource.password=anhzac12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=CXW9MxzKP90f8zpDSkjTcfbJfHUGh5ABQwErTyUidkdr